import { Deal } from "@/types";

export const deals: Deal[] = [
  {
    id: "pizza-deal-1",
    slug: "pizza-deal-1",
    name: { en: "Deal 1" },
    description: { en: "3 Small Pizza, 1 Liter Drink" },
    contents: [
      { text: { en: "Small Pizza" }, quantity: 3 },
      { text: { en: "1 Liter Drink" }, quantity: 1 },
    ],
    price: { amount: 1800, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Pizza Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    badges: ["featured", "limited-time"],
    active: true,
    sortOrder: 1,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "pizza-deal-2",
    slug: "pizza-deal-2",
    name: { en: "Deal 2" },
    description: { en: "3 Medium Pizza, 1.5 Liter Drink" },
    contents: [
      { text: { en: "Medium Pizza" }, quantity: 3 },
      { text: { en: "1.5 Liter Drink" }, quantity: 1 },
    ],
    price: { amount: 3300, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Pizza Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 2,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "pizza-deal-3",
    slug: "pizza-deal-3",
    name: { en: "Deal 3" },
    description: { en: "3 Large Pizza, 2 Liter Drink" },
    contents: [
      { text: { en: "Large Pizza" }, quantity: 3 },
      { text: { en: "2 Liter Drink" }, quantity: 1 },
    ],
    price: { amount: 4500, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Pizza Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 3,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "pizza-deal-4",
    slug: "pizza-deal-4",
    name: { en: "Deal 4" },
    description: { en: "1 Large Pizza, 1 Medium Pizza, 1 Small Pizza, 1.5 Liter Drink" },
    contents: [
      { text: { en: "Large Pizza" }, quantity: 1 },
      { text: { en: "Medium Pizza" }, quantity: 1 },
      { text: { en: "Small Pizza" }, quantity: 1 },
      { text: { en: "1.5 Liter Drink" }, quantity: 1 },
    ],
    price: { amount: 3200, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Pizza Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 4,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "krispo-deal-1",
    slug: "krispo-deal-1",
    name: { en: "Delicious Krispo Deal 1" },
    description: { en: "1 Zinger Burger, French Fries + 350 ml Drink" },
    contents: [
      { text: { en: "Zinger Burger" }, quantity: 1 },
      { text: { en: "French Fries" }, quantity: 1 },
      { text: { en: "350 ml Drink" }, quantity: 1 },
    ],
    price: { amount: 800, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Burger Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    badges: ["featured"],
    active: true,
    sortOrder: 5,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "krispo-deal-2",
    slug: "krispo-deal-2",
    name: { en: "Delicious Krispo Deal 2" },
    description: { en: "1 Chicken Burger, French Fries + 350 ml Drink" },
    contents: [
      { text: { en: "Chicken Burger" }, quantity: 1 },
      { text: { en: "French Fries" }, quantity: 1 },
      { text: { en: "350 ml Drink" }, quantity: 1 },
    ],
    price: { amount: 750, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Burger Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 6,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "krispo-deal-3",
    slug: "krispo-deal-3",
    name: { en: "Delicious Krispo Deal 3" },
    description: { en: "2 Zinger Burgers, 6 Pcs Hot Wings, French Fries + 1 Litre Drink" },
    contents: [
      { text: { en: "Zinger Burgers" }, quantity: 2 },
      { text: { en: "Hot Wings" }, quantity: 6 },
      { text: { en: "French Fries" }, quantity: 1 },
      { text: { en: "1 Litre Drink" }, quantity: 1 },
    ],
    price: { amount: 1700, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1610440042657-612c34d95e9f?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Combo Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 7,
    verification: { status: "verified", source: "printed-menu" },
  },
  {
    id: "krispo-deal-4",
    slug: "krispo-deal-4",
    name: { en: "Delicious Krispo Deal 4" },
    description: { en: "4 Zinger Burgers, 12 Pieces Hotshots, French Fries + 1.5 Litre Drink" },
    contents: [
      { text: { en: "Zinger Burgers" }, quantity: 4 },
      { text: { en: "Hotshots" }, quantity: 12 },
      { text: { en: "French Fries" }, quantity: 1 },
      { text: { en: "1.5 Litre Drink" }, quantity: 1 },
    ],
    price: { amount: 2800, currency: "PKR" },
    image: {
      src: "https://images.unsplash.com/photo-1605050965352-7a0e7aebbc9b?w=800&q=80&auto=format&fit=crop",
      alt: { en: "Family Deal" },
      width: 800,
      height: 600,
      placeholder: true,
    },
    active: true,
    sortOrder: 8,
    verification: { status: "verified", source: "printed-menu" },
  },
];
